### ISSUE TITLE
1.5.3-SNAPSHOT doesn't seem to exist in jCenter.

### ISSUE THREAD

**Issue by izeye** [asciidoctor/asciidoctor-gradle-plugin#151]
Should I add an additional repository to use snapshot?

**Comment by ysb33r** [comment]
1. JCenter does not host any snapshots
2. We don't publish snapshots for this plugin.

Best is to build it locally and publish it to your local M2. This would probably be as simple as `./gradlew build install`. You can re-use it by adding `mavenLocal()` to your consuming build script.

**Comment by izeye** [comment]
@ysb33r Thanks for the quick response. I guess it would be good to change the version in `README.adoc` to something in jCenter() like `1.5.2` to avoid confusion.

**Comment by mojavelinux** [comment]
I agree. It's probably also good to document why we aren't using oss.jfrog.org for publishing snapshots (@aalmiray has a strong opinion on this, which I support, but others don't know the story from looking at the README).

**Comment by aalmiray** [comment]
Sure, we should write down to a document why we do things like we do them today. Short summary in the meantime until we put forward said document:

 - we do not publish snapshot releases because plugin snapshots break one very important tenet from Gradle: reproducible builds. If a developer requires a snapshot release then we think this has to be a very conscious decision and they must bear the responsibility of building said snapshot. In this way they can be sure it's their version and not someone else's which might bring incompatibility problems.
- the default branch in github is `development` which is our working branch. `master` is set as the stable branch form which we make our releases. We made `development` the default because people kept sending PR's targeting `master`.
- listing `development` as default branch has the drawback you just experienced, that is, the readme is still in flux

**Comment by ysb33r** [comment]
I added a PR (#152) that can be a start for such a document.

**Comment by aalmiray** [comment]
lovely! :clap: thank you @ysb33r :smile:

**Comment by mojavelinux** [comment]
Nice!

**Comment by abelsromero** [comment]
Should we include the new document in the main README.adoc?
I feel it will go unnoticed unless it's in the front page.

**Comment by aalmiray** [comment]
Done and done. Thank you for all your help guys :clap:

**Comment by mojavelinux** [comment]
I think we still have the original problem the @izeye pointed out, which is that the README.adoc instructs the reader to use a SNAPSHOT version. People often arrive at the README.adoc to learn how to use the released version of the plugin. Therefore, I think that @izeye is right that the README.adoc should refer to the released version. Can we update?

**Comment by mojavelinux** [comment]
I should clarify this is on the development branch, which is the default branch that shows on GitHub.

**Comment by mojavelinux** [comment]
I send PR https://github.com/asciidoctor/asciidoctor-gradle-plugin/pull/165 to address.

**Comment by madhavhar** [comment]
Hi,
 I am configure Gradle  in Bamboo and am tying to build while job running build got field because some jcenter dependence files aren't download . I already done  proxy  configuration , bellow mention error came  
any one can help me please.

* What went wrong:
A problem occurred configuring root project 'parkingservice'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve org.asciidoctor:asciidoctor-gradle-plugin:1.5.3.
     Required by:
         :parkingservice:unspecified
      > Could not resolve org.asciidoctor:asciidoctor-gradle-plugin:1.5.3.
         > Could not get resource 'http://jcenter.bintray.com/org/asciidoctor/asciidoctor-gradle-plugin/1.5.3/asciidoctor-gradle-plugin-1.5.3.pom'.
            > Could not GET 'http://jcenter.bintray.com/org/asciidoctor/asciidoctor-gradle-plugin/1.5.3/asciidoctor-gradle-plugin-1.5.3.pom'. Received status code 407 from server: Proxy Authentication Required
      > Could not resolve org.asciidoctor:asciidoctor-gradle-plugin:1.5.3.
         > Could not get resource 'https://plugins.gradle.org/m2/org/asciidoctor/asciidoctor-gradle-plugin/1.5.3/asciidoctor-gradle-plugin-1.5.3.pom'.
            > Could not GET 'https://plugins.gradle.org/m2/org/asciidoctor/asciidoctor-gradle-plugin/1.5.3/asciidoctor-gradle-plugin-1.5.3.pom'. Received status code 407 from server: Proxy Authentication Required
