### ISSUE TITLE
asciidoctor-gradle-plugin build fails with "impossible to resolve dependencies"

### ISSUE THREAD

**Issue by rwinch** [asciidoctor/asciidoctor-gradle-plugin#528]
I'm wanting to work on gh-523 When running `./gradlew intTest` against master (8d324c24c37e6c649bde038257a2a456e008368f) the build fails with the following error:

```
[ivyResolve] :::: WARNINGS	
[ivyResolve] 	Error while parsing configuration resolve report /home/rwinch/code/asciidoctor/asciidoctor-gradle-plugin/testfixtures/offline-repo/build/tmp/ivypot/syncRemoteRepositories/org.codenarc-CodeNarc-caller-default.xml (java.text.ParseException: failed to parse report: /home/rwinch/code/asciidoctor/asciidoctor-gradle-plugin/testfixtures/offline-repo/build/tmp/ivypot/syncRemoteRepositories/org.codenarc-CodeNarc-caller-default.xml: An invalid XML character (Unicode: 0x3) was found in the value of attribute "details" and element is "artifact".)	
[ivyResolve] 	Error while parsing configuration resolve report /home/rwinch/code/asciidoctor/asciidoctor-gradle-plugin/testfixtures/offline-repo/build/tmp/ivypot/syncRemoteRepositories/org.codenarc-CodeNarc-caller-compile.xml (java.text.ParseException: failed to parse report: /home/rwinch/code/asciidoctor/asciidoctor-gradle-plugin/testfixtures/offline-repo/build/tmp/ivypot/syncRemoteRepositories/org.codenarc-CodeNarc-caller-compile.xml: An invalid XML character (Unicode: 0x3) was found in the value of attribute "details" and element is "artifact".)	
[ivyResolve] 	Error while parsing configuration resolve report /home/rwinch/code/asciidoctor/asciidoctor-gradle-plugin/testfixtures/offline-repo/build/tmp/ivypot/syncRemoteRepositories/org.codenarc-CodeNarc-caller-runtime.xml (java.text.ParseException: failed to parse report: /home/rwinch/code/asciidoctor/asciidoctor-gradle-plugin/testfixtures/offline-repo/build/tmp/ivypot/syncRemoteRepositories/org.codenarc-CodeNarc-caller-runtime.xml: An invalid XML character (Unicode: 0x3) was found in the value of attribute "details" and element is "artifact".)	
[ivyResolve] 		[FAILED     ] org.codehaus.groovy#groovy-all;2.3.11!groovy-all.jar: invalid sha1: expected=pk
...
: impossible to resolve dependencies:
	resolve failed - see output for details
[ivyResolve] 	==== BintrayJCenter: tried
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[ivyResolve] 	  https://jcenter.bintray.com/org/codehaus/groovy/groovy-all/2.3.11/groovy-all-2.3.11.jar
[ivyResolve] 		::::::::::::::::::::::::::::::::::::::::::::::

[ivyResolve] 		::              FAILED DOWNLOADS            ::
[ivyResolve] 		:: ^ see resolution messages for details  ^ ::
[ivyResolve] 		::::::::::::::::::::::::::::::::::::::::::::::
[ivyResolve] 		:: org.codehaus.groovy#groovy-all;2.3.11!groovy-all.jar
[ivyResolve] 		::::::::::::::::::::::::::::::::::::::::::::::
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at groovy.util.AntBuilder.performTask(AntBuilder.java:338)
	at groovy.util.AntBuilder.nodeCompleted(AntBuilder.java:283)
	at groovy.util.BuilderSupport.doInvokeMethod(BuilderSupport.java:154)
	at groovy.util.AntBuilder.doInvokeMethod(AntBuilder.java:218)
	at groovy.util.BuilderSupport.invokeMethod(BuilderSupport.java:67)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1017)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:994)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:182)
	at org.ysb33r.gradle.ivypot.remote.IvyAnt.ivyInstall(IvyAnt.groovy:93)
	at org.ysb33r.gradle.ivypot.remote.IvyAnt.access$0(IvyAnt.groovy)
	at org.ysb33r.gradle.ivypot.remote.IvyAnt$_resolve_closure3.doCall(IvyAnt.groovy:51)
	at org.ysb33r.gradle.ivypot.remote.IvyAnt$_resolve_closure3.call(IvyAnt.groovy)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2296)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2281)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2322)
	at org.ysb33r.gradle.ivypot.remote.IvyAnt.resolve(IvyAnt.groovy:50)
	at org.ysb33r.gradle.ivypot.remote.Downloader.main(Downloader.groovy:35)
Caused by: resolve failed - see output for details
	at org.apache.ivy.ant.IvyResolve.doExecute(IvyResolve.java:337)
	... 24 more
```

Here is a build scan https://gradle.com/s/4dmwvcvl775ao

Is there something I should be doing differently?

**Comment by ysb33r** [comment]
Mmm... that should just work out of the box

**Comment by slonopotamus** [comment]
They call it "bug" - when things do not behave as they should.

This is exactly the same error that happened on CI in #527.

**Comment by ysb33r** [comment]
I just did 
```
$ rm -rf testfixtures/offline-repo/build/repo/
$ gw syncRR
```
and I now managed to reproduce it locally !!

**Comment by ysb33r** [comment]
So there is a workaround for this during your development.  Comment out the `jcenter()` line 26 from `testfixtures/offline-repo/build.gradle` and run `rm -rf testfixtures/offline-repo/build/repo; ./gradlew syncRR`. 

It will take quite a while to sync, then you can re-enable that line and it all should work. There seems to be an issue with the ivypot plugin. I'll dig into that tomorrow if I can.

**Comment by ysb33r** [comment]
Tracking issue: https://github.com/ysb33r/ivypot-gradle-plugin/issues/47

**Comment by ysb33r** [comment]
This commit should solve it: https://github.com/asciidoctor/asciidoctor-gradle-plugin/commit/c9306721c2df9b5b403b12be61e26fc21f6d45ef

**Comment by ysb33r** [comment]
@rwinch If that commit works for you, then could close this issue?

**Comment by rwinch** [comment]
Thanks for the fast responses @ysb33r It is still failing for me. Initially it failed with the same error. I then invoked `git clean -dfx` to ensure that nothing was cached and reran `./gradlew `

The build takes a little longer to fail now, but it fails with a very similar (if not same error).

```
08:13:22.060 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] > Task :testfixtures-offline-repo:syncRemoteRepositories
08:14:06.625 [INFO] [system.out] [ivyResolve] :: problems summary ::
08:14:06.625 [INFO] [system.out] [ivyResolve] :::: WARNINGS
08:14:06.625 [INFO] [system.out] [ivyResolve]           [FAILED     ] org.codehaus.groovy#groovy-all;2.3.11!groovy-all.jar: invalid sha1: expected=pk
08:14:06.625 [INFO] [system.out] [ivyResolve]�qsf     meta-inf/��pk
08:14:06.625 [INFO] [system.out] [ivyResolve�qsf1�!��&meta-inf/manifest.mf�z]�۸}7��`�s����g���c&[4ݠ        �e�dۜ�d��<v}�%e[�x)
08:14:06.625 [INFO] [system.out] [ivyResolve] $�<����~�ʟy-������:��ŋ��g��7
> IDLE                                                                       /�b������|��
08:14:06.625 [INFO] [system.out] [ivyResolve] �e�|<!������r��_~��pb�q[�-�@�q>�t�~���|';����6����!>���잭v?�igw����=����'�q�^d�k�:�&u��#�4r���`@�s��5`����\
08:14:06.625 [INFO] [system.out] [ivyResolve] p�s*^�h�j�q���[sо��'�g�(+�)
08:14:06.626 [INFO] [system.out] [ivyResolve] ���%��u�3����q'`y�23�ڂ/`�����
                                                                             m�t��xq���������a�o��r��"�\
08:14:06.626 [INFO] [system.out] [ivyResolve] �u����1y�
                                                         �n�]?h����kz_p�)��
08:14:06.626 [INFO] [system.out] [ivyResolve] bͽω��4�       �y�t�f��rt�<�
08:14:06.626 [INFO] [system.out] [ivyResolve] l�����n>�[��k��=;cp��e��bӑ��#���±t�nϭ�?��gz������!����%���u�u��b+%�c��ӂc0��uic�:},��#��l�0v�9�֠������]�~��bw���dq��澱b���
                                                                                                                                                                                  p2�����sn�-t"i��ٔ�>{�8y$�
                                                                                                                                                                                                            b���<h`s�ia��@�3í�     ۸�y��
                        wϩxe�:_�.��op�&���<�g3�v8����&y�u{vag�av
08:14:06.626 [INFO] [system.out] [ivyResolve] �=��fj��s;q'�e��v�t$��ʉg���~e'n�4/�dh��kou�y���q�����k�]"�8���i����~��
08:14:06.626 [INFO] [system.out] [ivyResolve] �0�=r�b\��ro\�'g�����q�q
08:14:06.626 [INFO] [system.out] [ivyResolve] t<�ϳ�6�m����2����n��d\m��j9�i���3��u��=�4��ǹ����ɱj��'ǟ
                                                                                                         it�n�i�c�<[0�fй2�~�.uz�l�'�10t�j4tޒ_��mή=�<�s��q�y�ۘ�js'sl�����q�/�w�{����
                                                                                                                                                                                      ��;,�7'������}o   �<�/qh�����7�j�؋ɩ��гn�zm�����utc1�ڗ�
                              ,�^�un/����n�������}�   d�d>p�eo���c1/���o�1hh���n�a�ڷ��!]?l.���o���s�-�\*+
08:14:06.626 [INFO] [system.out] [ivyResolve] ��0-��(�����ԡj�꾜#��ߒo@��9o'[��'r�%8�
08:14:06.626 [INFO] [system.out] [ivyResolve] 6z��'x;�㠓��g�
08:14:06.627 [INFO] [system.out] [ivyResolve] �"q�*�o�78��ǻ\�يݱ��������j�^��/��j<,��]�'f���綍}u�
                                                                                                 }=u�d�q�k(u�_�~_����nv{���c�k}|o�ӫa~�y��՛�{e���1n$c��ec_�g���+�ӛ���m.�\��t���|�p��g�
                                                                                                                                                                                              �fȍt��mz�u�s��tn�y`��s����#`�%9**��<ק�3[ɉf�)�#��b�q�lӏ���-s���e�9b�#�v�����o��,*@����po:�'g"�;e8�{@�.~n"v�-ov8�p��� computed=f6b34997d04c1538ce451d3955298f46fdb4dbd4 (5297ms)
08:14:06.627 [ERROR] [system.err] Exception in thread "main" 
08:14:06.627 [INFO] [system.out] [ivyResolve]           [FAILED     ] org.codehaus.groovy#groovy-all;2.3.11!groovy-all.jar: invalid sha1: expected=pk
08:14:06.628 [ERROR] [system.err] : impossible to resolve dependencies:
08:14:06.628 [INFO] [system.out] [ivyResolve]�qsf     meta-inf/��pk
08:14:06.628 [ERROR] [system.err]       resolve failed - see output for details
08:14:06.628 [INFO] [system.out] [ivyResolve�qsf1�!��&meta-inf/manifest.mf�z]�۸}7��`�s����g���c&[4ݠ        �e�dۜ�d��<v}�%e[�x)
08:14:06.629 [ERROR] [system.err]       at org.apache.ivy.ant.IvyResolve.doExecute(IvyResolve.java:425)
08:14:06.629 [INFO] [system.out] [ivyResolve] $�<����~�ʟy-������:��ŋ��g��7
                                                                             /�b������|��
08:14:06.629 [ERROR] [system.err]       at org.apache.ivy.ant.IvyTask.execute(IvyTask.java:271)
08:14:06.629 [INFO] [system.out] [ivyResolve] �e�|<!������r��_~��pb�q[�-�@�q>�t�~���|';����6����!>���잭v?�igw����=����'�q�^d�k�:�&u��#�4r���`@�s��5`����\
08:14:06.629 [ERROR] [system.err]       at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
08:14:06.629 [INFO] [system.out] [ivyResolve] p�s*^�h�j�q���[sо��'�g�(+�)
08:14:06.630 [ERROR] [system.err]       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
08:14:06.630 [INFO] [system.out] [ivyResolve] ���%��u�3����q'`y�23�ڂ/`�����
                                                                             m�t��xq���������a�o��r��"�\
08:14:06.630 [INFO] [system.out] [ivyResolve] �u����1y�
                                                         �n�]?h����kz_p�)��
08:14:06.630 [INFO] [system.out] [ivyResolve] bͽω��4�       �y�t�f��rt�<�
08:14:06.630 [ERROR] [system.err]       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
08:14:06.630 [INFO] [system.out] [ivyResolve] l�����n>�[��k��=;cp��e��bӑ��#���±t�nϭ�?��gz������!����%���u�u��b+%�c��ӂc0��uic�:},��#��l�0v�9�֠������]�~��bw���dq��澱b���
                                                                                                                                                                                  p2�����sn�-t"i��ٔ�>{�8y$�
                                                                                                                                                                                                            b���<h`s�ia��@�3í�     ۸�y��
                        wϩxe�:_�.��op�&���<�g3�v8����&y�u{vag�av
08:14:06.630 [ERROR] [system.err]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
08:14:06.631 [INFO] [system.out] [ivyResolve] �=��fj��s;q'�e��v�t$��ʉg���~e'n�4/�dh��kou�y���q�����k�]"�8���i����~��
08:14:06.631 [ERROR] [system.err]       at java.lang.reflect.Method.invoke(Method.java:498)
08:14:06.631 [INFO] [system.out] [ivyResolve] �0�=r�b\��ro\�'g�����q�q
08:14:06.631 [ERROR] [system.err]       at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
08:14:06.631 [INFO] [system.out] [ivyResolve] t<�ϳ�6�m����2����n��d\m��j9�i���3��u��=�4��ǹ����ɱj��'ǟ
                                                                                                         it�n�i�c�<[0�fй2�~�.uz�l�'�10t�j4tޒ_��mή=�<�s��q�y�ۘ�js'sl�����q�/�w�{����
                                                                                                                                                                                      ��;,�7'������}o   �<�/qh�����7�j�؋ɩ��гn�zm�����utc1�ڗ�
                              ,�^�un/����n�������}�   d�d>p�eo���c1/���o�1hh���n�a�ڷ��!]?l.���o���s�-�\*+
08:14:06.631 [ERROR] [system.err]       at groovy.util.AntBuilder.performTask(AntBuilder.java:338)
08:14:06.631 [INFO] [system.out] [ivyResolve] ��0-��(�����ԡj�꾜#��ߒo@��9o'[��'r�%8�
08:14:06.631 [ERROR] [system.err]       at groovy.util.AntBuilder.nodeCompleted(AntBuilder.java:283)
08:14:06.631 [INFO] [system.out] [ivyResolve] 6z��'x;�㠓��g�
08:14:06.632 [ERROR] [system.err]       at groovy.util.BuilderSupport.doInvokeMethod(BuilderSupport.java:154)
08:14:06.632 [INFO] [system.out] [ivyResolve] �"q�*�o�78��ǻ\�يݱ��������j�^��/��j<,��]�'f���綍}u�
                                                                                                 }=u�d�q�k(u�_�~_����nv{���c�k}|o�ӫa~�y��՛�{e���1n$c��ec_�g���+�ӛ���m.�\��t���|�p��g�
                                                                                                                                                                                              �fȍt��mz�u�s��tn�y`��s����#`�%9**��<ק�3[ɉf�)�#��b�q�lӏ���-s���e�9b�#�v�����o��,*@����po:�'g"�;e8�{@�.~n"v�-ov8�
08:14:06.632 [ERROR] [system.err]       at groovy.util.AntBuilder.doInvokeMethod(AntBuilder.java:218)
08:14:06.632 [INFO] [system.out] p��� computed=f6b34997d04c1538ce451d3955298f46fdb4dbd4 (5297ms)
08:14:06.632 [ERROR] [system.err]       at groovy.util.BuilderSupport.invokeMethod(BuilderSupport.java:67)
08:14:06.632 [INFO] [system.out] [ivyResolve]   ==== BintrayJCenter: tried
08:14:06.632 [ERROR] [system.err]       at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1017)
08:14:06.632 [INFO] [system.out] [ivyResolve]     https://jcenter.bintray.com/org/codehaus/groovy/groovy-all/2.3.11/groovy-all-2.3.11.jar
08:14:06.632 [ERROR] [system.err]       at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:994)
08:14:06.632 [INFO] [system.out] [ivyResolve]           ::::::::::::::::::::::::::::::::::::::::::::::
08:14:06.632 [ERROR] [system.err]       at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:182)
08:14:06.632 [INFO] [system.out] [ivyResolve]           ::              FAILED DOWNLOADS            ::
08:14:06.633 [ERROR] [system.err]       at org.ysb33r.gradle.ivypot.remote.IvyAnt.ivyInstall(IvyAnt.groovy:93)
08:14:06.633 [INFO] [system.out] [ivyResolve]           :: ^ see resolution messages for details  ^ ::
08:14:06.633 [ERROR] [system.err]       at org.ysb33r.gradle.ivypot.remote.IvyAnt.access$0(IvyAnt.groovy)
08:14:06.633 [INFO] [system.out] [ivyResolve]           ::::::::::::::::::::::::::::::::::::::::::::::
08:14:06.633 [ERROR] [system.err]       at org.ysb33r.gradle.ivypot.remote.IvyAnt$_resolve_closure3.doCall(IvyAnt.groovy:51)
08:14:06.633 [INFO] [system.out] [ivyResolve]           :: org.codehaus.groovy#groovy-all;2.3.11!groovy-all.jar
08:14:06.633 [ERROR] [system.err]       at org.ysb33r.gradle.ivypot.remote.IvyAnt$_resolve_closure3.call(IvyAnt.groovy)
08:14:06.633 [INFO] [system.out] [ivyResolve]           ::::::::::::::::::::::::::::::::::::::::::::::
08:14:06.633 [ERROR] [system.err]       at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2296)
08:14:06.633 [ERROR] [system.err]       at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2281)
08:14:06.634 [ERROR] [system.err]       at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2322)
08:14:06.634 [ERROR] [system.err]       at org.ysb33r.gradle.ivypot.remote.IvyAnt.resolve(IvyAnt.groovy:50)
08:14:06.634 [ERROR] [system.err]       at org.ysb33r.gradle.ivypot.remote.Downloader.main(Downloader.groovy:35)
08:14:06.634 [ERROR] [system.err] Caused by: resolve failed - see output for details
08:14:06.634 [ERROR] [system.err]       at org.apache.ivy.ant.IvyResolve.doExecute(IvyResolve.java:337)
08:14:06.634 [ERROR] [system.err]       ... 24 more
08:14:06.692 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: FAILED
08:14:06.692 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command '/home/rwinch/.sdkman/candidates/java/8.0.222.hs-adpt/bin/java'' finished with exit value 1 (state: FAILED)
08:14:06.692 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Execute exec for :testfixtures-offline-repo:syncRemoteRepositories'
08:14:06.692 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Execute exec for :testfixtures-offline-repo:syncRemoteRepositories' completed
08:14:06.692 [DEBUG] [org.gradle.api.internal.tasks.execution.DefaultTaskFingerprinter] Fingerprinting property $1$1 (Output) for task ':testfixtures-offline-repo:syncRemoteRepositories'
08:14:06.692 [DEBUG] [org.gradle.api.internal.tasks.execution.DefaultTaskFingerprinter] Fingerprinting property $2$1 (Output) for task ':testfixtures-offline-repo:syncRemoteRepositories'
08:14:06.692 [DEBUG] [org.gradle.api.internal.tasks.execution.DefaultTaskFingerprinter] Fingerprinting property binaryRepoRoot (Output) for task ':testfixtures-offline-repo:syncRemoteRepositories'
08:14:06.692 [DEBUG] [org.gradle.api.internal.tasks.execution.DefaultTaskFingerprinter] Fingerprinting property repoRoot (Output) for task ':testfixtures-offline-repo:syncRemoteRepositories'
08:14:06.723 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter] Removed task artifact state for {} from context.
08:14:06.723 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Task :testfixtures-offline-repo:syncRemoteRepositories'
08:14:06.659 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] 
08:14:06.659 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] > Task :testfixtures-offline-repo:syncRemoteRepositories FAILED
08:14:06.723 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Task :testfixtures-offline-repo:syncRemoteRepositories' completed
08:14:06.723 [INFO] [org.gradle.execution.plan.DefaultPlanExecutor] :testfixtures-offline-repo:syncRemoteRepositories (Thread[Execution worker for ':' Thread 3,5,main]) completed. Took 46.674 secs.
08:14:06.723 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Execution worker for ':' Thread 3: released lock on :testfixtures-offline-repo
08:14:06.723 [DEBUG] [org.gradle.internal.work.DefaultWorkerLeaseService] Worker lease root.1.34 completed (1 worker(s) in use)
08:14:06.723 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Execution worker for ':' Thread 3: released lock on root.1.34
08:14:06.723 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Execution worker for ':' Thread 7,5,main]] finished, busy: 8.296 secs, idle: 38.371 secs
08:14:06.723 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Execution worker for ':' Thread 3,5,main]] finished, busy: 46.674 secs, idle: 0.001 secs
08:14:06.723 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Daemon worker Thread 2,5,main]] finished, busy: 12.878 secs, idle: 33.789 secs
08:14:06.723 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Execution worker for ':' Thread 2,5,main]] finished, busy: 18.748 secs, idle: 27.928 secs
08:14:06.723 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Execution worker for ':',5,main]] finished, busy: 17.126 secs, idle: 29.552 secs
08:14:06.723 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Execution worker for ':' Thread 4,5,main]] finished, busy: 12.028 secs, idle: 34.643 secs
08:14:06.723 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Execution worker for ':' Thread 6,5,main]] finished, busy: 9.348 secs, idle: 37.323 secs
08:14:06.723 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Execution worker for ':' Thread 5,5,main]] finished, busy: 10.199 secs, idle: 36.472 secs
08:14:06.724 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskExecutionGraph] Timing: Executing the DAG took 46.679 secs
08:14:06.726 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Run tasks'
08:14:06.726 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Run tasks' completed
08:14:06.727 [DEBUG] [org.gradle.internal.work.DefaultWorkerLeaseService] Worker lease root.1 completed (0 worker(s) in use)
08:14:06.727 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Daemon worker Thread 2: released lock on root.1
08:14:06.727 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
08:14:06.727 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
08:14:06.727 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
08:14:06.727 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
08:14:06.727 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':testfixtures-offline-repo:syncRemoteRepositories'.
08:14:06.727 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Process 'command '/home/rwinch/.sdkman/candidates/java/8.0.222.hs-adpt/bin/java'' finished with non-zero exit value 1
08:14:06.727 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
08:14:06.727 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
08:14:06.728 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]  Run with --scan to get full insights.
08:14:06.728 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
08:14:06.728 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
08:14:06.728 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':testfixtures-offline-repo:syncRemoteRepositories'.
08:14:06.728 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:148)
08:14:06.728 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:145)
08:14:06.728 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
08:14:06.728 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:138)
08:14:06.728 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionStateTaskExecuter.execute(ResolveBeforeExecutionStateTaskExecuter.java:75)
08:14:06.728 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
08:14:06.728 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
08:14:06.728 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.StartSnapshotTaskInputsBuildOperationTaskExecuter.execute(StartSnapshotTaskInputsBuildOperationTaskExecuter.java:62)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:73)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:49)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:49)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: org.gradle.process.internal.ExecException: Process 'command '/home/rwinch/.sdkman/candidates/java/8.0.222.hs-adpt/bin/java'' finished with non-zero exit value 1
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:396)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJavaExecAction.java:38)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.process.internal.DefaultExecActionFactory.javaexec(DefaultExecActionFactory.java:129)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.DefaultProject.javaexec(DefaultProject.java:1103)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.DefaultProject.javaexec(DefaultProject.java:1098)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.ysb33r.gradle.ivypot.OfflineRepositorySync.exec(OfflineRepositorySync.groovy:339)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:48)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:41)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:702)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:669)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:401)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:390)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:373)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:79)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:210)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
08:14:06.729 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)
08:14:06.730 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
08:14:06.730 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
08:14:06.730 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:33)
08:14:06.730 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:39)
08:14:06.730 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
08:14:06.730 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
08:14:06.730 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:35)
08:14:06.730 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
08:14:06.730 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:45)
08:14:06.730 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:31)
08:14:06.730 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:201)
08:14:06.730 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:70)
08:14:06.730 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:45)
08:14:06.730 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
08:14:06.730 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:43)
08:14:06.730 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:32)
08:14:06.730 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
08:14:06.730 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
08:14:06.730 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
08:14:06.730 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
08:14:06.730 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
08:14:06.730 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
08:14:06.730 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:77)
08:14:06.730 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
08:14:06.730 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
08:14:06.730 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
08:14:06.730 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)
08:14:06.730 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
08:14:06.730 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
08:14:06.730 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:117)
08:14:06.730 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 36 more
08:14:06.730 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
08:14:06.730 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
08:14:06.730 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org
08:14:06.730 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] 
08:14:06.730 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 51s
08:14:06.730 [LIFECYCLE] [org.gradle.internal.buildevents.TaskExecutionStatisticsReporter] 83 actionable tasks: 83 executed
08:14:06.752 [QUIET] [com.gradle.scan.plugin.BuildScanPlugin] 
08:14:06.753 [QUIET] [com.gradle.scan.plugin.BuildScanPlugin] Publishing build scan...

```

Here is the scan URL https://scans.gradle.com/s/p47wjhph5wxjw

**Comment by ysb33r** [comment]
@rwinch You already have the corrupted info in your local repository. `rm -rf testfixtures/offline-repo/build/repo`, run `./gradlew syncRR`, get a :coffee: and wait until it is done.

**Comment by ysb33r** [comment]
@rwinch Maybe you can save time by deleting any references to groovy 2.3.11 from that offline repo.

**Comment by rwinch** [comment]
> You already have the corrupted info in your local repository. rm -rf testfixtures/offline-repo/build/repo, run ./gradlew syncRR, get a coffee and wait until it is done.

Thanks for the pointer. This wasn't the issue since I ran `git clean -dfx` which removes anything that wasn't in the repository (including testfixtures/offline-repo/build).

I did figure out the issue. I'm embarrassed to say that I was running in master and the update was on develop-3.x branch. Switching over fixed it for me :man_facepalming: 

Thanks for your patience with me and thanks again for the quick turnaround.

**Comment by ysb33r** [comment]
> I did figure out the issue. I'm embarrassed to say that I was running in master and the update was on develop-3.x branch.

We've all been there. Looking forward to your contributions!
